/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package preguntas.respuestas.vista;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import preguntas.respuestas.modelo.ModeloPregunta;

/**
 *
 * @author Navas-JC
 */
public class VistaPreguntas2 extends javax.swing.JFrame {

    List<ModeloPregunta> listado = new ArrayList<>();

    Set<Integer> numeroAleatorio = new HashSet<>();
    String respuestaCorrecta;
    int puntajeAcumulado = 0;

    /**
     * Creates new form VistaPreguntas
     */
    public VistaPreguntas2() {
        initComponents();
        CrearPreguntas();
        jugar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnRetirarme = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jValorPregunta = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jMejorPuntuacion = new javax.swing.JLabel();
        btnRespuestaC = new javax.swing.JButton();
        btnRespuestaA = new javax.swing.JButton();
        btnRespuestaD = new javax.swing.JButton();
        btnRespuestaB = new javax.swing.JButton();
        btnSeguir = new javax.swing.JButton();
        txtPregunta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESCOGE LA RESPUESTA CORRECTA ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("A");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("D");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("C");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("B");

        btnRetirarme.setBackground(new java.awt.Color(0, 0, 204));
        btnRetirarme.setText("RETIRARME");
        btnRetirarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarmeActionPerformed(evt);
            }
        });

        jLabel13.setText("VALOR ");

        jValorPregunta.setBackground(new java.awt.Color(0, 0, 255));
        jValorPregunta.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jValorPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jValorPregunta.setText("USD 5000");
        jValorPregunta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 153)));

        jLabel15.setText("Mejor Puntuacion");

        jMejorPuntuacion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMejorPuntuacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMejorPuntuacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        btnRespuestaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestaCActionPerformed(evt);
            }
        });

        btnRespuestaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestaAActionPerformed(evt);
            }
        });

        btnRespuestaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestaDActionPerformed(evt);
            }
        });

        btnRespuestaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestaBActionPerformed(evt);
            }
        });

        btnSeguir.setText("SEGUIR");
        btnSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRespuestaC, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnRespuestaB, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRespuestaD, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addGap(45, 45, 45))
                            .addComponent(jValorPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(49, 49, 49))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jMejorPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(txtPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnRetirarme, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(btnRespuestaA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(428, 428, 428)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jMejorPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(18, 18, 18)
                                                .addComponent(jValorPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(btnRespuestaC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(btnRespuestaB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnRespuestaD, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetirarme)
                    .addComponent(btnSeguir))
                .addGap(38, 38, 38))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(244, 244, 244)
                    .addComponent(btnRespuestaA, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRespuestaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaAActionPerformed
        // TODO add your handling code here:

        if (respuestaCorrecta.equals(btnRespuestaA.getText())) {
            JOptionPane.showMessageDialog(null, "Respuesta correcta");
            puntajeAcumulado += 5000;
        } else {
            JOptionPane.showMessageDialog(null, "Respuesta Incorrecta");
            setVisible(false);
            Vista vista = new Vista();
            vista.setVisible(true);
        }
    }//GEN-LAST:event_btnRespuestaAActionPerformed

    private void btnRespuestaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaBActionPerformed

        if (respuestaCorrecta.equals(btnRespuestaB.getText())) {
            JOptionPane.showMessageDialog(null, "Respuesta correcta");
            puntajeAcumulado += 5000;
        } else {
            JOptionPane.showMessageDialog(null, "Respuesta Incorrecta");
            setVisible(false);
            Vista vista = new Vista();
            vista.setVisible(true);
        }
    }//GEN-LAST:event_btnRespuestaBActionPerformed


    private void btnRespuestaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaDActionPerformed
        if (respuestaCorrecta.equals(btnRespuestaD.getText())) {
            JOptionPane.showMessageDialog(null, "Respuesta correcta");
            puntajeAcumulado += 5000;
        } else {
            JOptionPane.showMessageDialog(null, "Respuesta Incorrecta");
            setVisible(false);
            Vista vista = new Vista();
            vista.setVisible(true);
        }
    }//GEN-LAST:event_btnRespuestaDActionPerformed

    private void btnRespuestaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaCActionPerformed
        if (respuestaCorrecta.equals(btnRespuestaC.getText())) {
            JOptionPane.showMessageDialog(null, "Respuesta correcta");
            puntajeAcumulado += 5000;
        } else {
            JOptionPane.showMessageDialog(null, "Respuesta Incorrecta");
            setVisible(false);
            Vista vista = new Vista();
            vista.setVisible(true);
        }
    }//GEN-LAST:event_btnRespuestaCActionPerformed

    private void btnRetirarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarmeActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, "Juego terminado");
        JOptionPane.showMessageDialog(null, "Puntaje acumulado: " + puntajeAcumulado);
        setVisible(false);
            Vista vista = new Vista();
            vista.setVisible(true);
    }//GEN-LAST:event_btnRetirarmeActionPerformed

    private void btnSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguirActionPerformed
        setVisible(false);
        
        VistaPreguntas3 vistaPreguntas3 = new VistaPreguntas3();
        vistaPreguntas3.jMejorPuntuacion.setText(""+ puntajeAcumulado);
        
        vistaPreguntas3.setVisible(true);


    }//GEN-LAST:event_btnSeguirActionPerformed

    public void jugar() {
        int numeroPregunta = aleatorioNoRepetido();
        txtPregunta.setText(listado.get(numeroPregunta).getPregunta());
        btnRespuestaA.setText(listado.get(numeroPregunta).getRespuesA());
        btnRespuestaB.setText(listado.get(numeroPregunta).getRespuestaB());
        btnRespuestaC.setText(listado.get(numeroPregunta).getRespuestaC());
        btnRespuestaD.setText(listado.get(numeroPregunta).getRespuestaD());
        respuestaCorrecta = listado.get(numeroPregunta).getRespuestaCorrecta();
    }

    public void CrearPreguntas() {
       
         listado.add(new ModeloPregunta( "¿Cuál es el nombre del río más largo del mundo?", "Rio Nilo", "Río Amazonas", "Río Magdalena", "Río Danubio", "Río Amazonas"));
         listado.add(new ModeloPregunta( "¿Cuál es el país que tiene forma de bota?", "Italia", "Chile", "Holanda", "España", "Italia"));
         listado.add(new ModeloPregunta( " ¿Cuál es la ciudad de los rascacielos?", "New York", "Tokio", "Dubai", "Hong Kong", "New York"));
         listado.add(new ModeloPregunta( "¿En qué país se encuentra ubicada la Casa Rosada?", "Colombia", "Argentina", "Venezuela", "Chile", "Argentina"));
         listado.add(new ModeloPregunta( "¿Cuál es la única ciudad que está en dos continentes distintos?", "Berlin", "Estambul", "Barcelona", "Moscu", "Estambul"));
        // pregunta.add(new ModeloPregunta( "¿Cuál es la capital de Pakistán?", "Bagdag", "Islamabad", "Marrekech", "Marruecos", "Islamabad"));
        // pregunta.add(new ModeloPregunta( "¿Cuándo terminó la II Guerra Mundial?", "1945", "1947", "1946", "1943", "1945"));
        // pregunta.add(new ModeloPregunta( "¿En qué año llegó Cristobal Colón a América?", "1429", "1492", "1592", "1494", "1492"));
        // pregunta.add(new ModeloPregunta( "¿En qué país se usó la primera bomba atómica?", "Rusia", "EEUU", "China", "Japón", "Japón"));
        // pregunta.add(new ModeloPregunta( " ¿Cuál es el idioma más antiguo que pervive en Europa?", "Latín", "Fancés", "Vasco", "Inglés", "Vasco"));

    }

    public int aleatorioNoRepetido() {
        int devolver = 0;
        boolean b = false;
        while (!b) {
            int random = (int) (5 * Math.random());
            if (!numeroAleatorio.contains(random)) {
                numeroAleatorio.add(random);
                b = true;
                devolver = random;
            }
        }
        return devolver;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRespuestaA;
    private javax.swing.JButton btnRespuestaB;
    private javax.swing.JButton btnRespuestaC;
    private javax.swing.JButton btnRespuestaD;
    private javax.swing.JButton btnRetirarme;
    private javax.swing.JButton btnSeguir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jMejorPuntuacion;
    private javax.swing.JLabel jValorPregunta;
    private javax.swing.JTextField txtPregunta;
    // End of variables declaration//GEN-END:variables
}
